### ISSUE TITLE
Simplecast Connector Issues 

### ISSUE THREAD

**Issue by JoseAnaya28** [status-im/airbyte-custom-connector#12]
@apentori 
- Episode stream is only fetching 100 records.
- Analytic Episode stream is only fetching 5 records.

- Can we get https://api.simplecast.com/analytics?episode={episode_id}? Just downloads analytics . Example: "downloads": {
        "href": "https://api.simplecast.com/analytics/downloads?episode=1c25c46e-8532-4bde-abe2-88158f5b6c7f"
    }

**Comment by apentori** [comment]
The API is well done and the pagination is easy to add.

There is something that bother me however: the analytics endpoints like : `analytics/location` or `analytics/episode?podcast=id` don't appear in the documentation. Will they disappear ?

Adding the `analytics?epidode` endpoint is doable, however  how do i name the object ? `analytic_episode` is already used for the object from `analytics/episodes?podcast`.

**Comment by apentori** [comment]
```
airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://api.simplecast.com/analytics?episode=6677f85d-b41e-4c2e-ae28-0f22b1132455, Response Code: 429, Response Text: {"status":429,"href":null,"error_message":"You have exceeded your api key request quota for this account","error":"too_many_requests"}
```
We might have an issue here, it's probably due to my multiple test

**Comment by apentori** [comment]
https://github.com/status-im/airbyte-custom-connector/commit/204812e8f8af9f74dff7de896de379dea310d4d3

I will update the connector later, when the API has reset the quotq

**Comment by apentori** [comment]
https://help.simplecast.com/en/articles/2724796-simplecast-2-0-api#versioning

> We will add a versioning option to the header soon. But, rest assured, we won't make any breaking changes in the meantime. 

We should be good for the old endpoint.

**Comment by JoseAnaya28** [comment]
> Adding the `analytics?epidode` endpoint is doable, however how do i name the object ? `analytic_episode` is already used for the object from `analytics/episodes?podcast`.

We can name it: `analytics_episode_downloads`

**Comment by apentori** [comment]
The table `analytic_episode_download` is already available in `bi.prod`, i totally forgot to send a message.
 Does this table and `analytic_episode_download_by_interval' hold all the data that you need ?

**Comment by JoseAnaya28** [comment]
Awesome! Looks like it, I'll test it and let you know if there's any issues
