### ISSUE TITLE
Discord Connector - Get Members Roles

### ISSUE THREAD

**Issue by JoseAnaya28** [status-im/airbyte-custom-connector#13]
We've received a request to show the number of users with a specific role within the logos server. Currently we aren't fetching the role data for users. 

Can we add this to the connector?

**Comment by apentori** [comment]
Roles are fetch into `guild_role` and each member has a list of role.

**Comment by jakubgs** [comment]
Wasn't this already done in:

* https://github.com/status-im/airbyte-custom-connector/pull/15

**Comment by apentori** [comment]
It was, i forgot to close the issue after merging the PR
